import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { trpc} from "../utils/trpc";
import { signIn, signOut} from "next-auth/react";
import React from "react";
import TodoList from "../components/todo-list";

const handleSignIn = (e: { preventDefault: () => void; }) => {
  e.preventDefault();
  signIn();
};

const Home: NextPage = () => {
  const { data: session } = useSession(); 
  const utils = trpc.useContext();

  const createTodo = trpc.useMutation(["todos.create"], {
    onSuccess: () => {
      utils.invalidateQueries(["todos.getAll"]);
      setName("")
    },
  });

  const [name, setName] = React.useState("");

  const handleCreate = (e: { preventDefault: () => void; }) => {
    e.preventDefault();
    createTodo.mutate({ title: name });
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold">
          Todo list
        </h1>

          { session && (
            <div>              
              <form onSubmit={handleCreate} className="flex flex-col">
                <input className="input input-bordered" type="text" value={name} onInput={(e) => setName(e.currentTarget.value)} />

                <button className="btn mt-3" type="submit">Create todo</button>
              </form>

              <br />

              <TodoList />

            </div>
          )} 

          { !session && (
            <p onClick={handleSignIn}> not logged in </p>
          )}
          
      </main>
    </>
  );
};

export default Home;
